version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/python-test
hooks:
  BeforeInstall:
    - location: home/ubuntu/python-test/scripts/install_dependencies.sh
      runas: root
  ApplicationStart:
    - location: home/ubuntu/python-test/scripts/start_server.sh
      runas: root
  ValidateService:
    - location: home/ubuntu/python-test/scripts/validate_service.sh
      runas: root


