version: 0.0
os: linux
files:
  - source: / 
    destination: /home/ec2-user/python-test
permissions:
  - object: /home/ec2-user/python-test
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: install-dependencies
      timeout: 300
  ApplicationStart:
    - location: start-flask.sh
      timeout: 300

