version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/python-test
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: /install-dependencies
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      runas: root 


